modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="MIT License"
issueTrackerURL="https://github.com/ItamarDenkberg/All-You-Can-Eat/issues" #optional
[[mods]] #mandatory
modId="allyoucaneat" #mandatory
version="0.6" #mandatory
displayName="All You Can Eat" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/all-you-can-eat" #optional
logoFile="allyoucaneat.png" #optional
credits="" #optional
authors="Itamar Denkberg" #optional
description='''
'''
[[dependencies.allyoucaneat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.allyoucaneat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
